name: shalfie
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.4.0

  # State Management
  flutter_riverpod: ^2.5.1

  # Local Database
  sembast: ^3.5.0
  path_provider: ^2.1.2

  # Network & API
  dio: ^5.4.0
  connectivity_plus: ^6.0.3

  # EPUB Reader
  flutter_epub_reader: ^1.3.4

  # UI / Helpers
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  skeletonizer: ^2.1.0

  # Navigation
  go_router: ^14.0.0

  # Other
  uuid: ^4.4.0
  xml2json: ^6.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/

image_picker: ^1.1.0
firebase_storage: ^12.0.0
fluttertoast: ^8.0.9
